# -*- coding: utf-8 -*-
"""
/***************************************************************************
 processing_demo
                                 A QGIS plugin
 sample description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-03
        copyright            : (C) 2026 by jsonsingh.com
        email                : qgis-plugin@jsonsingh.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load processing_demo class from file processing_demo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .processing_demo import processing_demo
    return processing_demo(iface)
